/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleAnalyticsRouteImport } from './routes/console/analytics'
import { Route as ConsoleBillingRouteImport } from './routes/console/billing'
import { Route as ConsoleKeysRouteImport } from './routes/console/keys'
import { Route as ConsoleLogsRouteImport } from './routes/console/logs'
import { Route as ConsoleOverviewRouteImport } from './routes/console/overview'
import { Route as ConsoleUsageRouteImport } from './routes/console/usage'
import { Route as ConsoleWalletRouteImport } from './routes/console/wallet'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsModelsRouteImport } from './routes/docs/models'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs/troubleshooting'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DocsApiAnthropicRouteImport } from './routes/docs/api/anthropic'
import { Route as DocsApiOpenaiRouteImport } from './routes/docs/api/openai'
import { Route as DocsClientsClaudeCodeRouteImport } from './routes/docs/clients/claude-code'
import { Route as DocsClientsCodexRouteImport } from './routes/docs/clients/codex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAnalyticsRoute = ConsoleAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBillingRoute = ConsoleBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleKeysRoute = ConsoleKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleLogsRoute = ConsoleLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOverviewRoute = ConsoleOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsageRoute = ConsoleUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleWalletRoute = ConsoleWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ConsoleRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsModelsRoute = DocsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiAnthropicRoute = DocsApiAnthropicRouteImport.update({
  id: '/api/anthropic',
  path: '/api/anthropic',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiOpenaiRoute = DocsApiOpenaiRouteImport.update({
  id: '/api/openai',
  path: '/api/openai',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsClaudeCodeRoute = DocsClientsClaudeCodeRouteImport.update({
  id: '/clients/claude-code',
  path: '/clients/claude-code',
  getParentRoute: () => DocsRoute,
} as any)
const DocsClientsCodexRoute = DocsClientsCodexRouteImport.update({
  id: '/clients/codex',
  path: '/clients/codex',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/register': typeof RegisterRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/billing': typeof ConsoleBillingRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/logs': typeof ConsoleLogsRoute
  '/console/overview': typeof ConsoleOverviewRoute
  '/console/usage': typeof ConsoleUsageRoute
  '/console/wallet': typeof ConsoleWalletRoute
  '/docs/models': typeof DocsModelsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/console/': typeof ConsoleIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/api/anthropic': typeof DocsApiAnthropicRoute
  '/docs/api/openai': typeof DocsApiOpenaiRoute
  '/docs/clients/claude-code': typeof DocsClientsClaudeCodeRoute
  '/docs/clients/codex': typeof DocsClientsCodexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/register': typeof RegisterRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/billing': typeof ConsoleBillingRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/logs': typeof ConsoleLogsRoute
  '/console/overview': typeof ConsoleOverviewRoute
  '/console/usage': typeof ConsoleUsageRoute
  '/console/wallet': typeof ConsoleWalletRoute
  '/docs/models': typeof DocsModelsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/console': typeof ConsoleIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/api/anthropic': typeof DocsApiAnthropicRoute
  '/docs/api/openai': typeof DocsApiOpenaiRoute
  '/docs/clients/claude-code': typeof DocsClientsClaudeCodeRoute
  '/docs/clients/codex': typeof DocsClientsCodexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/register': typeof RegisterRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/billing': typeof ConsoleBillingRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/logs': typeof ConsoleLogsRoute
  '/console/overview': typeof ConsoleOverviewRoute
  '/console/usage': typeof ConsoleUsageRoute
  '/console/wallet': typeof ConsoleWalletRoute
  '/docs/models': typeof DocsModelsRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/console/': typeof ConsoleIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/api/anthropic': typeof DocsApiAnthropicRoute
  '/docs/api/openai': typeof DocsApiOpenaiRoute
  '/docs/clients/claude-code': typeof DocsClientsClaudeCodeRoute
  '/docs/clients/codex': typeof DocsClientsCodexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/contact'
    | '/docs'
    | '/login'
    | '/models'
    | '/register'
    | '/console/analytics'
    | '/console/billing'
    | '/console/keys'
    | '/console/logs'
    | '/console/overview'
    | '/console/usage'
    | '/console/wallet'
    | '/docs/models'
    | '/docs/quickstart'
    | '/docs/troubleshooting'
    | '/console/'
    | '/docs/'
    | '/api/auth/$'
    | '/docs/api/anthropic'
    | '/docs/api/openai'
    | '/docs/clients/claude-code'
    | '/docs/clients/codex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/models'
    | '/register'
    | '/console/analytics'
    | '/console/billing'
    | '/console/keys'
    | '/console/logs'
    | '/console/overview'
    | '/console/usage'
    | '/console/wallet'
    | '/docs/models'
    | '/docs/quickstart'
    | '/docs/troubleshooting'
    | '/console'
    | '/docs'
    | '/api/auth/$'
    | '/docs/api/anthropic'
    | '/docs/api/openai'
    | '/docs/clients/claude-code'
    | '/docs/clients/codex'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/contact'
    | '/docs'
    | '/login'
    | '/models'
    | '/register'
    | '/console/analytics'
    | '/console/billing'
    | '/console/keys'
    | '/console/logs'
    | '/console/overview'
    | '/console/usage'
    | '/console/wallet'
    | '/docs/models'
    | '/docs/quickstart'
    | '/docs/troubleshooting'
    | '/console/'
    | '/docs/'
    | '/api/auth/$'
    | '/docs/api/anthropic'
    | '/docs/api/openai'
    | '/docs/clients/claude-code'
    | '/docs/clients/codex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/analytics': {
      id: '/console/analytics'
      path: '/analytics'
      fullPath: '/console/analytics'
      preLoaderRoute: typeof ConsoleAnalyticsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/billing': {
      id: '/console/billing'
      path: '/billing'
      fullPath: '/console/billing'
      preLoaderRoute: typeof ConsoleBillingRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/keys': {
      id: '/console/keys'
      path: '/keys'
      fullPath: '/console/keys'
      preLoaderRoute: typeof ConsoleKeysRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/logs': {
      id: '/console/logs'
      path: '/logs'
      fullPath: '/console/logs'
      preLoaderRoute: typeof ConsoleLogsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/overview': {
      id: '/console/overview'
      path: '/overview'
      fullPath: '/console/overview'
      preLoaderRoute: typeof ConsoleOverviewRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/usage': {
      id: '/console/usage'
      path: '/usage'
      fullPath: '/console/usage'
      preLoaderRoute: typeof ConsoleUsageRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/wallet': {
      id: '/console/wallet'
      path: '/wallet'
      fullPath: '/console/wallet'
      preLoaderRoute: typeof ConsoleWalletRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/models': {
      id: '/docs/models'
      path: '/models'
      fullPath: '/docs/models'
      preLoaderRoute: typeof DocsModelsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api/anthropic': {
      id: '/docs/api/anthropic'
      path: '/api/anthropic'
      fullPath: '/docs/api/anthropic'
      preLoaderRoute: typeof DocsApiAnthropicRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api/openai': {
      id: '/docs/api/openai'
      path: '/api/openai'
      fullPath: '/docs/api/openai'
      preLoaderRoute: typeof DocsApiOpenaiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients/claude-code': {
      id: '/docs/clients/claude-code'
      path: '/clients/claude-code'
      fullPath: '/docs/clients/claude-code'
      preLoaderRoute: typeof DocsClientsClaudeCodeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/clients/codex': {
      id: '/docs/clients/codex'
      path: '/clients/codex'
      fullPath: '/docs/clients/codex'
      preLoaderRoute: typeof DocsClientsCodexRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAnalyticsRoute: typeof ConsoleAnalyticsRoute
  ConsoleBillingRoute: typeof ConsoleBillingRoute
  ConsoleKeysRoute: typeof ConsoleKeysRoute
  ConsoleLogsRoute: typeof ConsoleLogsRoute
  ConsoleOverviewRoute: typeof ConsoleOverviewRoute
  ConsoleUsageRoute: typeof ConsoleUsageRoute
  ConsoleWalletRoute: typeof ConsoleWalletRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAnalyticsRoute: ConsoleAnalyticsRoute,
  ConsoleBillingRoute: ConsoleBillingRoute,
  ConsoleKeysRoute: ConsoleKeysRoute,
  ConsoleLogsRoute: ConsoleLogsRoute,
  ConsoleOverviewRoute: ConsoleOverviewRoute,
  ConsoleUsageRoute: ConsoleUsageRoute,
  ConsoleWalletRoute: ConsoleWalletRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface DocsRouteChildren {
  DocsModelsRoute: typeof DocsModelsRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiAnthropicRoute: typeof DocsApiAnthropicRoute
  DocsApiOpenaiRoute: typeof DocsApiOpenaiRoute
  DocsClientsClaudeCodeRoute: typeof DocsClientsClaudeCodeRoute
  DocsClientsCodexRoute: typeof DocsClientsCodexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsModelsRoute: DocsModelsRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiAnthropicRoute: DocsApiAnthropicRoute,
  DocsApiOpenaiRoute: DocsApiOpenaiRoute,
  DocsClientsClaudeCodeRoute: DocsClientsClaudeCodeRoute,
  DocsClientsCodexRoute: DocsClientsCodexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
